//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 07:10:50 PM EDT 
//


package org.sirrus.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ti"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ev" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="ec" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                             &lt;element name="se" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                             &lt;element name="loc"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="geo" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;simpleContent&gt;
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                               &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                                               &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                                             &lt;/extension&gt;
 *                                           &lt;/simpleContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="start" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;simpleContent&gt;
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                                               &lt;attribute name="dir" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                                               &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                                               &lt;attribute name="extent" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                                             &lt;/extension&gt;
 *                                           &lt;/simpleContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="valid"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                                     &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="text"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="delay" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                 &lt;attribute name="tv" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="fv" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                 &lt;attribute name="at" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ti"
})
@XmlRootElement(name = "incident")
public class Incident {

    @XmlElement(required = true)
    protected Incident.Ti ti;

    /**
     * Gets the value of the ti property.
     * 
     * @return
     *     possible object is
     *     {@link Incident.Ti }
     *     
     */
    public Incident.Ti getTi() {
        return ti;
    }

    /**
     * Sets the value of the ti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Incident.Ti }
     *     
     */
    public void setTi(Incident.Ti value) {
        this.ti = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ev" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="ec" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *                   &lt;element name="se" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *                   &lt;element name="loc"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="geo" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;simpleContent&gt;
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                                     &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *                                     &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *                                   &lt;/extension&gt;
     *                                 &lt;/simpleContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="start" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;simpleContent&gt;
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                                     &lt;attribute name="dir" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                                     &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                                     &lt;attribute name="extent" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                                   &lt;/extension&gt;
     *                                 &lt;/simpleContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="valid"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *                           &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="text"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="delay" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *       &lt;attribute name="tv" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="fv" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *       &lt;attribute name="at" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ev"
    })
    public static class Ti {

        protected List<Incident.Ti.Ev> ev;
        @XmlAttribute(name = "table")
        protected Byte table;
        @XmlAttribute(name = "tv")
        protected String tv;
        @XmlAttribute(name = "fv")
        protected Float fv;
        @XmlAttribute(name = "at")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar at;

        /**
         * Gets the value of the ev property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ev property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEv().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Incident.Ti.Ev }
         * 
         * 
         */
        public List<Incident.Ti.Ev> getEv() {
            if (ev == null) {
                ev = new ArrayList<Incident.Ti.Ev>();
            }
            return this.ev;
        }

        /**
         * Gets the value of the table property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getTable() {
            return table;
        }

        /**
         * Sets the value of the table property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setTable(Byte value) {
            this.table = value;
        }

        /**
         * Gets the value of the tv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTv() {
            return tv;
        }

        /**
         * Sets the value of the tv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTv(String value) {
            this.tv = value;
        }

        /**
         * Gets the value of the fv property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getFv() {
            return fv;
        }

        /**
         * Sets the value of the fv property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setFv(Float value) {
            this.fv = value;
        }

        /**
         * Gets the value of the at property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAt() {
            return at;
        }

        /**
         * Sets the value of the at property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAt(XMLGregorianCalendar value) {
            this.at = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="ec" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
         *         &lt;element name="se" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
         *         &lt;element name="loc"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="geo" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;simpleContent&gt;
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                           &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         *                           &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         *                         &lt;/extension&gt;
         *                       &lt;/simpleContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="start" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;simpleContent&gt;
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *                           &lt;attribute name="dir" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *                           &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *                           &lt;attribute name="extent" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *                         &lt;/extension&gt;
         *                       &lt;/simpleContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="valid"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *                 &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="text"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="delay" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "ec",
            "se",
            "loc",
            "valid",
            "text",
            "delay"
        })
        public static class Ev {

            protected int id;
            protected short ec;
            protected byte se;
            @XmlElement(required = true)
            protected Incident.Ti.Ev.Loc loc;
            @XmlElement(required = true)
            protected Incident.Ti.Ev.Valid valid;
            @XmlElement(required = true)
            protected Incident.Ti.Ev.Text text;
            protected byte delay;

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the ec property.
             * 
             */
            public short getEc() {
                return ec;
            }

            /**
             * Sets the value of the ec property.
             * 
             */
            public void setEc(short value) {
                this.ec = value;
            }

            /**
             * Gets the value of the se property.
             * 
             */
            public byte getSe() {
                return se;
            }

            /**
             * Sets the value of the se property.
             * 
             */
            public void setSe(byte value) {
                this.se = value;
            }

            /**
             * Gets the value of the loc property.
             * 
             * @return
             *     possible object is
             *     {@link Incident.Ti.Ev.Loc }
             *     
             */
            public Incident.Ti.Ev.Loc getLoc() {
                return loc;
            }

            /**
             * Sets the value of the loc property.
             * 
             * @param value
             *     allowed object is
             *     {@link Incident.Ti.Ev.Loc }
             *     
             */
            public void setLoc(Incident.Ti.Ev.Loc value) {
                this.loc = value;
            }

            /**
             * Gets the value of the valid property.
             * 
             * @return
             *     possible object is
             *     {@link Incident.Ti.Ev.Valid }
             *     
             */
            public Incident.Ti.Ev.Valid getValid() {
                return valid;
            }

            /**
             * Sets the value of the valid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Incident.Ti.Ev.Valid }
             *     
             */
            public void setValid(Incident.Ti.Ev.Valid value) {
                this.valid = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link Incident.Ti.Ev.Text }
             *     
             */
            public Incident.Ti.Ev.Text getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link Incident.Ti.Ev.Text }
             *     
             */
            public void setText(Incident.Ti.Ev.Text value) {
                this.text = value;
            }

            /**
             * Gets the value of the delay property.
             * 
             */
            public byte getDelay() {
                return delay;
            }

            /**
             * Sets the value of the delay property.
             * 
             */
            public void setDelay(byte value) {
                this.delay = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="geo" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;simpleContent&gt;
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *                 &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
             *                 &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
             *               &lt;/extension&gt;
             *             &lt;/simpleContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="start" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;simpleContent&gt;
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
             *                 &lt;attribute name="dir" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
             *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
             *                 &lt;attribute name="extent" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
             *               &lt;/extension&gt;
             *             &lt;/simpleContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "geo",
                "addr",
                "start"
            })
            public static class Loc {

                protected Incident.Ti.Ev.Loc.Geo geo;
                protected String addr;
                protected Incident.Ti.Ev.Loc.Start start;
                @XmlAttribute(name = "type")
                protected String type;

                /**
                 * Gets the value of the geo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Incident.Ti.Ev.Loc.Geo }
                 *     
                 */
                public Incident.Ti.Ev.Loc.Geo getGeo() {
                    return geo;
                }

                /**
                 * Sets the value of the geo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Incident.Ti.Ev.Loc.Geo }
                 *     
                 */
                public void setGeo(Incident.Ti.Ev.Loc.Geo value) {
                    this.geo = value;
                }

                /**
                 * Gets the value of the addr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddr() {
                    return addr;
                }

                /**
                 * Sets the value of the addr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddr(String value) {
                    this.addr = value;
                }

                /**
                 * Gets the value of the start property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Incident.Ti.Ev.Loc.Start }
                 *     
                 */
                public Incident.Ti.Ev.Loc.Start getStart() {
                    return start;
                }

                /**
                 * Sets the value of the start property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Incident.Ti.Ev.Loc.Start }
                 *     
                 */
                public void setStart(Incident.Ti.Ev.Loc.Start value) {
                    this.start = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;simpleContent&gt;
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                 *       &lt;attribute name="lon" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                 *       &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                 *     &lt;/extension&gt;
                 *   &lt;/simpleContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Geo {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "lon")
                    protected Float lon;
                    @XmlAttribute(name = "lat")
                    protected Float lat;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the lon property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public Float getLon() {
                        return lon;
                    }

                    /**
                     * Sets the value of the lon property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setLon(Float value) {
                        this.lon = value;
                    }

                    /**
                     * Gets the value of the lat property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public Float getLat() {
                        return lat;
                    }

                    /**
                     * Sets the value of the lat property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setLat(Float value) {
                        this.lat = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;simpleContent&gt;
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
                 *       &lt;attribute name="dir" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
                 *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
                 *       &lt;attribute name="extent" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
                 *     &lt;/extension&gt;
                 *   &lt;/simpleContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Start {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "id")
                    protected Short id;
                    @XmlAttribute(name = "dir")
                    protected Byte dir;
                    @XmlAttribute(name = "offset")
                    protected Byte offset;
                    @XmlAttribute(name = "extent")
                    protected Byte extent;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Short }
                     *     
                     */
                    public Short getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Short }
                     *     
                     */
                    public void setId(Short value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the dir property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getDir() {
                        return dir;
                    }

                    /**
                     * Sets the value of the dir property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setDir(Byte value) {
                        this.dir = value;
                    }

                    /**
                     * Gets the value of the offset property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getOffset() {
                        return offset;
                    }

                    /**
                     * Sets the value of the offset property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setOffset(Byte value) {
                        this.offset = value;
                    }

                    /**
                     * Gets the value of the extent property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getExtent() {
                        return extent;
                    }

                    /**
                     * Sets the value of the extent property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setExtent(Byte value) {
                        this.extent = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Text {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "lang")
                protected String lang;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the lang property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLang() {
                    return lang;
                }

                /**
                 * Sets the value of the lang property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLang(String value) {
                    this.lang = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
             *       &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Valid {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "start")
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar start;
                @XmlAttribute(name = "end")
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar end;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the start property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getStart() {
                    return start;
                }

                /**
                 * Sets the value of the start property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setStart(XMLGregorianCalendar value) {
                    this.start = value;
                }

                /**
                 * Gets the value of the end property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getEnd() {
                    return end;
                }

                /**
                 * Sets the value of the end property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setEnd(XMLGregorianCalendar value) {
                    this.end = value;
                }

            }

        }

    }

}
