//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 07:10:50 PM EDT 
//


package org.sirrus.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sirrus.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sirrus.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Incident }
     * 
     */
    public Incident createIncident() {
        return new Incident();
    }

    /**
     * Create an instance of {@link Incident.Ti }
     * 
     */
    public Incident.Ti createIncidentTi() {
        return new Incident.Ti();
    }

    /**
     * Create an instance of {@link Incident.Ti.Ev }
     * 
     */
    public Incident.Ti.Ev createIncidentTiEv() {
        return new Incident.Ti.Ev();
    }

    /**
     * Create an instance of {@link Incident.Ti.Ev.Loc }
     * 
     */
    public Incident.Ti.Ev.Loc createIncidentTiEvLoc() {
        return new Incident.Ti.Ev.Loc();
    }

    /**
     * Create an instance of {@link Incident.Ti.Ev.Valid }
     * 
     */
    public Incident.Ti.Ev.Valid createIncidentTiEvValid() {
        return new Incident.Ti.Ev.Valid();
    }

    /**
     * Create an instance of {@link Incident.Ti.Ev.Text }
     * 
     */
    public Incident.Ti.Ev.Text createIncidentTiEvText() {
        return new Incident.Ti.Ev.Text();
    }

    /**
     * Create an instance of {@link Incident.Ti.Ev.Loc.Geo }
     * 
     */
    public Incident.Ti.Ev.Loc.Geo createIncidentTiEvLocGeo() {
        return new Incident.Ti.Ev.Loc.Geo();
    }

    /**
     * Create an instance of {@link Incident.Ti.Ev.Loc.Start }
     * 
     */
    public Incident.Ti.Ev.Loc.Start createIncidentTiEvLocStart() {
        return new Incident.Ti.Ev.Loc.Start();
    }

}
